#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'

// Generate the same 8-character hex hash used in the build
const buildHash = createHash('sha1')
  .update(Date.now().toString())
  .digest('hex')
  .slice(0, 8)

const swPath = resolve('dist', 'sw.js')

// Wait for sw.js to be generated by VitePWA
let attempts = 0
const maxAttempts = 200 // 2 seconds total (200 * 10ms)

function tryPatchSw() {
  attempts++
  
  if (existsSync(swPath)) {
    console.log(`[patch-sw] Found sw.js on attempt ${attempts}`)
    try {
      const content = readFileSync(swPath, 'utf-8')
      const patched = content.replace(/__BUILD_HASH__/g, buildHash)
      writeFileSync(swPath, patched, 'utf-8')
      console.log(`[patch-sw] Successfully replaced __BUILD_HASH__ with ${buildHash}`)
    } catch (err) {
      console.error(`[patch-sw] Error patching sw.js:`, err.message)
      process.exit(1)
    }
  } else if (attempts < maxAttempts) {
    setTimeout(tryPatchSw, 10)
  } else {
    console.error(`[patch-sw] sw.js not found after ${attempts} attempts`)
    process.exit(1)
  }
}

console.log('[patch-sw] Waiting for VitePWA to generate sw.js...')
tryPatchSw()

